name: Python 3 Minutes Script

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/python-timer.yml'

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: تشغيل سكربت Python لمدة 3 دقائق
        run: python3 .github/scripts/timer.py
